# convolution and correlation


In [1]:
import numpy as np
import matplotlib.pyplot as plt
import scipy

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.6/60.6 kB 618.9 kB/s eta 0:00:00a 0:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 38.2/38.2 MB 1.7 MB/s eta 0:00:0000:0100:01


In [2]:
length = int(input("Enter length of sequence: "))
x = np.arange(length)
h = np.arange(length)

#x input
for i in range(length):
    x[i]=int(input("Enter x["+str(i)+"]: "))
    
#h input
for i in range(length):
    h[i]=int(input("Enter h["+str(i)+"]: "))

In [7]:
row = length*2-1
col = length
x_mat = np.zeros((row,col))
x_mat.shape

(7, 4)

In [8]:
count=0
for i in range(length):
    for j in range(length):
        x_mat[count+j][i] = x[j]
    count+=1

In [9]:
x_mat

array([[1., 0., 0., 0.],
       [2., 1., 0., 0.],
       [3., 2., 1., 0.],
       [4., 3., 2., 1.],
       [0., 4., 3., 2.],
       [0., 0., 4., 3.],
       [0., 0., 0., 4.]])

In [10]:
result = x_mat.dot(h)

In [11]:
result

array([ 1.,  3.,  6., 10.,  9.,  7.,  4.])

In [12]:
result = np.convolve(x,h)

In [13]:
result

array([ 1,  3,  6, 10,  9,  7,  4])

In [5]:
result = np.correlate(x,h,mode='full')

In [6]:
result

array([  9,  26,  50,  80, 115,  96,  74,  50,  25])